Name: Linux.Triage.UAC
Description: |
  This artifact is built from the UAC project.

TargetDirectories:
  - uac/artifacts

ArtifactTemplate: templates/Linux.Triage.UAC.yaml
RegExToGlob:
  "%user_home%": "/home/*"
  "%temp_directory%": "/tmp/"
Output:
  - output/Linux.Triage.UAC.yaml
  - output/Linux.Triage.UAC.zip
  - docs/content/docs/Linux.Triage.UAC/Linux.Triage.UAC.yaml
  - docs/content/docs/Linux.Triage.UAC/Linux.Triage.UAC.zip

StateFile: docs/content/docs/Linux.Triage.UAC/rules/Linux.Triage.UAC.json

# The following are invalid yaml upstream and do not load correctly.
SkipFiles:
  - spotlight.yaml
  - package_owns_file.yaml
  - strings_running_processes.yaml
  - sudo_lectured.yaml
  - virt-top.yaml

PathSep: /

Transformer: uac
TargetRegex: ".yaml$"

Debug: false
MakeAllTarget: true
